version: "3"
services:
  app:
    container_name: mongo-pagination
    restart: always
    build: ./
    ports:
      - "8181:8484"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"